site_name: csv_taker
site_description: Test task
repo_url: https://github.com/RodionChachura/csv_taker
site_dir: site
copyright: Copyright &copy; 2018, <a href="https://github.com/RodionChachura">RodionChachura</a>.
dev_addr: 0.0.0.0:8001

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
